### ISSUE TITLE
yosemite4-n: heartbeat LED not working

### ISSUE THREAD

**Issue by RickyWu-wiwynn** [Wiwynn/fb_openbmc#3]
Need to enable [phosphor-led-sysfs](https://github.com/openbmc/phosphor-led-sysfs) to control the heartbeat LED.
Set heartbeat LED in dts but it didn't be created in /sys/class/leds/heartbeat.

DTS:
```
	leds {
		compatible = "gpio-leds";
		heartbeat {
			label = "heartbeat";
			gpios = <&gpio7 4 GPIO_ACTIVE_LOW>; // GPIO228
		};
	};
```

yosemite4.cfg:
```
# LED
CONFIG_NEW_LEDS=y
CONFIG_LEDS_CLASS=y
CONFIG_LEDS_GPIO=y
CONFIG_LEDS_TRIGGERS=y
CONFIG_LEDS_TRIGGER_TIMER=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=y
CONFIG_LEDS_TRIGGER_DEFAULT_ON=y
```

**Comment by RickyWu-wiwynn** [comment]
Could build the driver after 'devtool reset linux-nuvoton'.

Added phosphor-led-manager service and led.yaml.
Looks like service is waiting for bmc_booted and BMC state is not ready.
```
root@yosemite4-n:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.NotReady
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.Off
Error finding '/xyz/openbmc_project/state/host0' service: Input/output error

root@yosemite4-n:~# ps | grep led
  574 root      4336 S    /usr/bin/mapper wait /xyz/openbmc_project/led/groups/bmc_booted
  631 root     12692 S    /usr/libexec/phosphor-led-sysfs/phosphor-ledcontroller -p /sys/class/leds/heartbeat
  778 root      4204 S    /usr/bin/mapper wait /xyz/openbmc_project/led/groups
  849 root     13256 S    phosphor-ledmanager
  853 root      3464 S    grep led
```

**Comment by RickyWu-wiwynn** [comment]
bmc_booted will wait for all service targets in multi-user.target.
```
root@yosemite4-n:~# cat /lib/systemd/system/obmc-led-group-start\@bmc_booted.service.d/bmc_booted.conf
[Unit]
Wants=multi-user.target
After=multi-user.target
```

**Comment by jc849** [comment]
1. please reference below commit to update LED manager build flow:
https://gerrit.openbmc.org/plugins/gitiles/openbmc/openbmc/+/538683f3af153b0a3381790a7bfbd2696b17f9d5

2. change overwrite to yosemite4-n or create a new recipe for nuvoton platfrom phosphor state manager to avoid waiting non-exist services.
Reference below commits:
https://github.com/Wiwynn/fb_openbmc/blob/Ricky/yosemite4-n_v2024.06.01/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager_%25.bbappend#L7
https://gerrit.openbmc.org/plugins/gitiles/openbmc/openbmc/+/a43085ea8dbdbea161bdf6970b96d468c875b9b3

**Comment by RickyWu-wiwynn** [comment]
Heartbeat LED is functional after adding obmc-led feature.
